### ISSUE TITLE
AutoPlay Xbox question

### ISSUE THREAD

**Issue by mfkl** [flecoqui/TestMediaApp#1]
Hi,

Is the following code from `OnFileActivated` supposed to work on Xbox, whether the app is launched or not? 

```
else if (string.Equals(args.Verb, "PlayCD", StringComparison.OrdinalIgnoreCase))
{
    LogMessage("Event Play CD");
    p.AutoPlay(args.Verb);
}
else if (string.Equals(args.Verb, "PlayDVD", StringComparison.OrdinalIgnoreCase))
{
    LogMessage("Event Play DVD");
    p.AutoPlay(args.Verb);
}
else if (string.Equals(args.Verb, "PlayBD", StringComparison.OrdinalIgnoreCase))
{
    LogMessage("Event Play BluRay");
    p.AutoPlay(args.Verb);
}
```

On my end, when I insert an audio CD, it launches the Store (which does not seem to work in Developer Mode, so blank screen) to download Groove.

From https://docs.microsoft.com/en-us/windows/uwp/launch-resume/auto-launching-with-autoplay:

> The Windows.Devices.Portable.StorageDevice APIs are part of the desktop device family. Apps can use these APIs only on Windows 10 devices in the desktop device family, such as PCs.

If I understand correctly, AutoPlay is not available for 3rd party apps on Xbox. Do you confirm?

**Comment by flecoqui** [comment]
Sorry for the delay, yes AutoPlay is not available for 3rd party apps on XBOX One.
