### ISSUE TITLE
Missing DeviceInput.cs file to compile AudioVideoPlayer project

### ISSUE THREAD

**Issue by TheWebartist** [flecoqui/TestMediaApp#2]
Hi,
The file DeviceInput.cs (in Models namespace) is required but not on the repository, so the AudioVideoPlayer cannot be compiled/deployed.

![image](https://user-images.githubusercontent.com/5822487/50892570-23386f00-13ff-11e9-8213-02dd8eaf2640.png)

Thanks

**Comment by flecoqui** [comment]
Oops, sorry updated few minutes ago for the release of the new version supporting PlayTo scenarios with UPNP Devices and HEOS Devices.

**Comment by TheWebartist** [comment]
No problem, 
Thanks, it's now solved.
Bonne journée :)
